### ISSUE TITLE
Custom hostname ignored for compute node 

### ISSUE THREAD

**Issue by pannon** [joyent/sdc-adminui#3] opened 2015-01-28 00:09 UTC
Not sure whether this is the right repo for this issue, please see below:

Custom hostname is dropped after initial setup of compute nodes.
I have retested this multiple times, even on different SDC releases (affecting latest build as well).

Steps to reproduce:
- click on Setup for new compute node
- select custom hostname
- type in hostname, save

Impact:
- after compute node reboots hostname reverts back to ID

Tried this multiple times after factory reset - same result.

**Comment by kevinykchan** [comment] 2015-01-28 08:33
Some findings, hostname IS passed to cnapi properly during setup, here is the output of the job parameters after performing setup with a custom hostname via adminui

```
{
  "nic_action": "update",
  "amqp_host": "rabbitmq.dev-coal-1.joyent.us",
  "cnapi_url": "http://10.99.99.22",
  "assets_url": "http://10.99.99.8",
  "server_uuid": "564d5a69-2e4c-f6da-2d9c-8b046d64b5e2",
  "overprovision_ratio": 1,
  "hostname": "test"
}
```

**Comment by pannon** [comment] 2015-01-28 08:47
Same here, and the node is only known by its ID - hostname is completely missing from the admin-ui.

```
{
    "nic_action": "update",
    "amqp_host": "rabbitmq.xxxxx",
    "cnapi_url": "http://10.65.65.16",
    "assets_url": "http://10.65.65.2",
    "server_uuid": "00000000-0000-0000-0000-002590fbff6c",
    "overprovision_ratio": 1,
    "hostname": "sdc-compute03"
}
```

**Comment by kevinykchan** [comment] 2015-01-28 09:05
@orlandov passing this to you, looks like the issue is in cnapi.

**Comment by orlandov** [comment] 2015-01-29 17:53
Hey guys, this should be fixed as of https://github.com/joyent/sdc-cnapi/commit/fd67d757131831c037e98dba811aa4a5e5cd41f9 - sorry for the trouble!

**Closed by orlandov** 2015-01-29 17:53 UTC

**Comment by pannon** [comment] 2015-01-30 07:42
Yes, it is! Just tested it and have all compute nodes showing up in adminui with custom hostnames. Thanks!
